import type { Metadata } from "next";
import {
  Epilogue
} from "next/font/google";
import "./globals.css";

const epilogue = Epilogue({
  variable: "--font-epilogue",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${epilogue.variable} font-[family-name:var(--font-clash-display)] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
